apiVersion: v1
kind: Service
metadata:
  labels:
    run: demo-prometheus
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
    dns.alpha.kubernetes.io/external: prometheus.mlab.fyi
  name: demo-prometheus
  namespace: default
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    run: demo-prometheus
  sessionAffinity: None
  externalIPs:
    - 104.196.164.214
  # type: LoadBalancer
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: demo-prometheus
  name: demo-prometheus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-prometheus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: demo-prometheus
      labels:
        run: demo-prometheus
    spec:
      containers:
      - image: soltesz/demo-prometheus:test
        name: demo-prometheus
        ports:
          - containerPort: 9090
        resources:
          requests:
            memory: "3Gi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /prometheus
          name: demo-prometheus-disk
      #volumes:
      #- name: demo-prometheus-disk
      #  # This GCE PD must already exist.
      #  gcePersistentDisk:
      #    pdName: demo-prometheus-disk-500g
      #    fsType: ext4
      volumes:
      - name: demo-prometheus-disk
        persistentVolumeClaim:
          claimName: auto-disk0
