apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-grafana-disk0
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: grafana-server
  name: grafana-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: grafana-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: grafana-server
      labels:
        run: grafana-server
    spec:
      containers:
      - image: grafana/grafana:4.1.1
        name: grafana-server
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-admin
              key: grafana-password
        ports:
          - containerPort: 3000
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
        # TODO: add support for SSL certificates, so logins are secure.
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: auto-grafana-disk0
