apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      # Used to match pre-existing pods that may be affected during updates.
      run: prometheus-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  # Pod template.
  template:
    metadata:
      labels:
        # Note: run=prometheus-server should match a service config with a
        # public IP and port so that it is publically accessible.
        run: prometheus-server
    spec:
      containers:
      - image: prom/prometheus:v1.5.2
        # Note: this value appears to be ignored and the actual pod name is
        # derived from the Deployment.metadata.name. However, removing this
        # value results in a configuration error.
        name: prometheus-server
        args: ["-config.file=/etc/prometheus/prometheus.yml",
               "-storage.local.path=/prometheus",
               "-storage.local.retention=1440h",
               "-web.console.libraries=/usr/share/prometheus/console_libraries",
               "-web.console.templates=/usr/share/prometheus/consoles"]
        ports:
          - containerPort: 9090
        resources:
          requests:
            memory: "3Gi"
            cpu: "500m"
        volumeMounts:
        # /prometheus stores all metric data. Declared as VOLUME in base image.
        - mountPath: /prometheus
          name: prometheus-storage
          subPath: prometheus-data
        # /legacy-targets should contain legacy target configuration files.
        - mountPath: /legacy-targets
          name: prometheus-storage
          subPath: legacy-targets
        # The prometheus.yml configuration file.
        - name: prometheus-config
          mountPath: /etc/prometheus
      # Disks created manually, can be named here explicitly using
      # gcePersistentDisk instead of the persistentVolumeClaim.
      volumes:
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: auto-prometheus-disk0
      - name: prometheus-config
        configMap:
          name: prometheus-config
