apiVersion: v1
kind: Service
metadata:
  name: pushgateway-public-service
  namespace: default
spec:
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    # Pods with labels matching this key/value pair will be publically
    # accessible through the service IP and port.
    run: pushgateway-server
  sessionAffinity: None
  # Use the same static IP as used for Prometheus.
  externalIPs:
    # Use the same IP as above, since we're on a different port.
    - 104.196.164.214
  type: ClusterIP
